"""
AMR-QTS Strategy Modules — Core Data Structures
Shared classes and functions for modules.
"""

from enum import IntEnum
from dataclasses import dataclass, field
import numpy as np
import pandas as pd
from src.regime.regime_detector import Regime

class Direction(IntEnum):
    LONG = 1
    SHORT = -1

@dataclass
class Signal:
    """A trade signal generated by a strategy module."""
    timestamp: pd.Timestamp       # When signal was generated
    symbol: str
    direction: Direction
    module: str                   # 'trend', 'meanrev', 'highvol'
    entry_price: float
    stop_loss: float
    take_profit: float
    risk_pct: float = 0.5         # Defaults to 0.5% (pass specific from separate settings if overridden)
    atr_at_entry: float = 0.0
    regime: Regime = Regime.NEUTRAL
    regime_confidence: float = 0.0
    rr_ratio: float = 0.0        # Reward:Risk ratio
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        risk_dist = abs(self.entry_price - self.stop_loss)
        reward_dist = abs(self.take_profit - self.entry_price)
        self.rr_ratio = reward_dist / risk_dist if risk_dist > 0 else 0


@dataclass
class Trade:
    """A completed trade (signal + outcome)."""
    signal: Signal
    exit_price: float
    exit_time: pd.Timestamp
    exit_reason: str              # 'tp', 'sl', 'time', 'regime_change', 'trail'
    pnl_pips: float = 0.0
    pnl_r: float = 0.0           # PnL in R-units
    bars_held: int = 0
    mfe_pips: float = 0.0        # Max favorable excursion
    mae_pips: float = 0.0        # Max adverse excursion

    def __post_init__(self):
        direction = self.signal.direction
        entry = self.signal.entry_price
        risk_dist = abs(entry - self.signal.stop_loss)
        self.pnl_pips = (self.exit_price - entry) * direction * 10000
        self.pnl_r = self.pnl_pips / (risk_dist * 10000) if risk_dist > 0 else 0


def detect_h4_structure(h4_df: pd.DataFrame) -> pd.Series:
    """
    Detect H4 structural trend: HH/HL = uptrend, LH/LL = downtrend.
    Returns Series of 1 (uptrend), -1 (downtrend), 0 (no trend).
    """
    highs = h4_df['high']
    lows = h4_df['low']

    # Use 5-bar swing detection
    swing_h = highs.rolling(5, center=True).max() == highs
    swing_l = lows.rolling(5, center=True).min() == lows

    structure = pd.Series(0, index=h4_df.index)

    prev_swing_high = np.nan
    prev_swing_low = np.nan

    for i in range(len(h4_df)):
        if swing_h.iloc[i]:
            if not np.isnan(prev_swing_high):
                if highs.iloc[i] > prev_swing_high:
                    structure.iloc[i] = 1  # Higher high
                elif highs.iloc[i] < prev_swing_high:
                    structure.iloc[i] = -1  # Lower high
            prev_swing_high = highs.iloc[i]

        if swing_l.iloc[i]:
            if not np.isnan(prev_swing_low):
                if lows.iloc[i] > prev_swing_low:
                    structure.iloc[i] = max(structure.iloc[i], 1)  # Higher low
                elif lows.iloc[i] < prev_swing_low:
                    structure.iloc[i] = min(structure.iloc[i], -1)  # Lower low
            prev_swing_low = lows.iloc[i]

    # Forward fill the structure signal
    structure = structure.replace(0, np.nan).ffill().fillna(0).astype(int)
    return structure
