"""
AMR-QTS Strategy Modules — Layer C

Three strategy modules gated by HMM regime detection:
  Module 1: Trend Continuation (TRENDING regime)
  Module 2: Mean Reversion (RANGING regime)
  Module 3: High Volatility Protocol (HIGH_VOL regime)

Each module:
  - Takes 15m entry data + H1 regime data + H4 structure data
  - Returns Signal objects with entry, SL, TP, direction, risk
  - Respects session filters and regime confidence thresholds
"""

import sys
from pathlib import Path
from enum import IntEnum
from dataclasses import dataclass, field
from typing import Optional
from abc import ABC, abstractmethod

import numpy as np
import pandas as pd
from ta.trend import ADXIndicator, EMAIndicator
from ta.volatility import AverageTrueRange, BollingerBands
from ta.momentum import RSIIndicator

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from config.settings import (
    # Trend params
    TREND_BREAKOUT_BARS, TREND_ATR_EXPANSION, TREND_RSI_LONG_RANGE,
    TREND_RSI_SHORT_RANGE, TREND_SL_ATR_MULT, TREND_RR_PRIMARY,
    TREND_RR_TRAIL_ACTIVATION, TREND_MFE_RETRACE_EXIT,
    # Mean Rev params
    MR_RSI_PERIOD, MR_RSI_OVERSOLD, MR_RSI_OVERBOUGHT,
    MR_BB_PERIOD, MR_BB_STD, MR_SL_ATR_MULT, MR_MIN_RR, MR_TIME_EXIT_BARS,
    # High Vol params
    HV_BAR_RANGE_MULT, HV_BODY_RATIO, HV_ATR_EXPANSION,
    HV_SL_ATR_MULT, HV_MIN_RR, HV_RISK_REDUCTION,
    # General
    ADX_PERIOD, ATR_PERIOD, EMA_FAST, EMA_SLOW, EMA_PROXIMITY_THRESHOLD,
    BASE_RISK_PCT, MAX_SLIPPAGE_PIPS, SPREAD_PIPS,
    HMM_MIN_CONFIDENCE,
)
from src.regime.regime_detector import Regime


# ============================================================
# SIGNAL DATA STRUCTURES
# ============================================================

class Direction(IntEnum):
    LONG = 1
    SHORT = -1


@dataclass
class Signal:
    """A trade signal generated by a strategy module."""
    timestamp: pd.Timestamp       # When signal was generated
    symbol: str
    direction: Direction
    module: str                   # 'trend', 'meanrev', 'highvol'
    entry_price: float
    stop_loss: float
    take_profit: float
    risk_pct: float = BASE_RISK_PCT
    atr_at_entry: float = 0.0
    regime: Regime = Regime.NEUTRAL
    regime_confidence: float = 0.0
    rr_ratio: float = 0.0        # Reward:Risk ratio
    metadata: dict = field(default_factory=dict)

    def __post_init__(self):
        risk_dist = abs(self.entry_price - self.stop_loss)
        reward_dist = abs(self.take_profit - self.entry_price)
        self.rr_ratio = reward_dist / risk_dist if risk_dist > 0 else 0


@dataclass
class Trade:
    """A completed trade (signal + outcome)."""
    signal: Signal
    exit_price: float
    exit_time: pd.Timestamp
    exit_reason: str              # 'tp', 'sl', 'time', 'regime_change', 'trail'
    pnl_pips: float = 0.0
    pnl_r: float = 0.0           # PnL in R-units
    bars_held: int = 0
    mfe_pips: float = 0.0        # Max favorable excursion
    mae_pips: float = 0.0        # Max adverse excursion

    def __post_init__(self):
        direction = self.signal.direction
        entry = self.signal.entry_price
        risk_dist = abs(entry - self.signal.stop_loss)
        self.pnl_pips = (self.exit_price - entry) * direction * 10000
        self.pnl_r = self.pnl_pips / (risk_dist * 10000) if risk_dist > 0 else 0


# ============================================================
# INDICATOR HELPERS
# ============================================================

def compute_indicators(df: pd.DataFrame) -> pd.DataFrame:
    """Add common technical indicators to an OHLC DataFrame."""
    out = df.copy()

    # ATR
    atr_ind = AverageTrueRange(high=df['high'], low=df['low'], close=df['close'],
                               window=ATR_PERIOD, fillna=False)
    out['atr'] = atr_ind.average_true_range()

    # RSI
    rsi_ind = RSIIndicator(close=df['close'], window=MR_RSI_PERIOD, fillna=False)
    out['rsi'] = rsi_ind.rsi()

    # EMAs
    out['ema_fast'] = EMAIndicator(close=df['close'], window=EMA_FAST, fillna=False).ema_indicator()
    out['ema_slow'] = EMAIndicator(close=df['close'], window=EMA_SLOW, fillna=False).ema_indicator()

    # ADX
    adx_ind = ADXIndicator(high=df['high'], low=df['low'], close=df['close'],
                           window=ADX_PERIOD, fillna=False)
    out['adx'] = adx_ind.adx()
    out['plus_di'] = adx_ind.adx_pos()
    out['minus_di'] = adx_ind.adx_neg()

    # Bollinger Bands
    bb = BollingerBands(close=df['close'], window=MR_BB_PERIOD, window_dev=MR_BB_STD, fillna=False)
    out['bb_upper'] = bb.bollinger_hband()
    out['bb_lower'] = bb.bollinger_lband()
    out['bb_mid'] = bb.bollinger_mavg()

    # Bar range
    out['bar_range'] = df['high'] - df['low']
    out['body'] = abs(df['close'] - df['open'])
    out['body_ratio'] = out['body'] / out['bar_range'].replace(0, np.nan)

    # Rolling highs/lows for breakout (shifted by 1 so current bar can break out)
    out['high_20'] = df['high'].rolling(TREND_BREAKOUT_BARS).max().shift(1)
    out['low_20'] = df['low'].rolling(TREND_BREAKOUT_BARS).min().shift(1)

    # Average bar range for expansion checks
    out['avg_range_5'] = out['bar_range'].rolling(5).mean().shift(1)
    out['avg_range_20'] = out['bar_range'].rolling(20).mean().shift(1)

    # ATR change (3-bar smoothed for HighVol module)
    out['atr_change_pct'] = (out['atr'] - out['atr'].shift(3)) / out['atr'].shift(3)

    return out


def detect_h4_structure(h4_df: pd.DataFrame) -> pd.Series:
    """
    Detect H4 structural trend: HH/HL = uptrend, LH/LL = downtrend.
    Returns Series of 1 (uptrend), -1 (downtrend), 0 (no trend).
    """
    highs = h4_df['high']
    lows = h4_df['low']

    # Use 5-bar swing detection
    swing_h = highs.rolling(5, center=True).max() == highs
    swing_l = lows.rolling(5, center=True).min() == lows

    structure = pd.Series(0, index=h4_df.index)

    prev_swing_high = np.nan
    prev_swing_low = np.nan

    for i in range(len(h4_df)):
        if swing_h.iloc[i]:
            if not np.isnan(prev_swing_high):
                if highs.iloc[i] > prev_swing_high:
                    structure.iloc[i] = 1  # Higher high
                elif highs.iloc[i] < prev_swing_high:
                    structure.iloc[i] = -1  # Lower high
            prev_swing_high = highs.iloc[i]

        if swing_l.iloc[i]:
            if not np.isnan(prev_swing_low):
                if lows.iloc[i] > prev_swing_low:
                    structure.iloc[i] = max(structure.iloc[i], 1)  # Higher low
                elif lows.iloc[i] < prev_swing_low:
                    structure.iloc[i] = min(structure.iloc[i], -1)  # Lower low
            prev_swing_low = lows.iloc[i]

    # Forward fill the structure signal
    structure = structure.replace(0, np.nan).ffill().fillna(0).astype(int)
    return structure


# ============================================================
# MODULE 1 — TREND CONTINUATION
# ============================================================

class TrendStrategy:
    """
    Module 1: Trend Continuation
    Activation: TRENDING regime with >70% confidence

    Entry: 20-bar breakout + ATR expansion + RSI filter
    SL: ATR(14) x 1.5
    TP: 1:2 RR, trailing at 1:1
    """

    def __init__(self, symbol: str = "EURUSD"):
        self.symbol = symbol
        self.name = "trend"

    def generate_signals(
        self,
        entry_df: pd.DataFrame,    # 15m data with indicators
        h1_regime: pd.DataFrame,  # Regime predictions (regime, confidence)
        h4_structure: pd.Series,  # H4 structural trend (1/-1/0)
    ) -> list[Signal]:
        """Scan for trend continuation entries on 15m data."""
        signals = []
        df = compute_indicators(entry_df)

        for i in range(TREND_BREAKOUT_BARS + 5, len(df)):
            bar = df.iloc[i]
            ts = df.index[i]

            # Skip if indicators not ready
            if pd.isna(bar['atr']) or pd.isna(bar['rsi']) or pd.isna(bar['ema_slow']):
                continue

            # --- Regime gate ---
            regime_row = self._get_regime_at(ts, h1_regime)
            if regime_row is None:
                continue
            if regime_row['regime'] != Regime.TRENDING:
                continue
            if regime_row['confidence'] < HMM_MIN_CONFIDENCE:
                continue

            # --- H4 structure confirmation ---
            h4_dir = self._get_h4_at(ts, h4_structure)

            atr = bar['atr']
            if atr <= 0:
                continue

            # --- LONG setup ---
            if (h4_dir >= 0 and  # H4 not downtrending
                bar['close'] > bar['high_20'] and  # 20-bar breakout
                bar['close'] > bar['ema_slow'] and  # Above EMA200
                bar['bar_range'] > TREND_ATR_EXPANSION * bar['avg_range_5'] and  # ATR expansion
                TREND_RSI_LONG_RANGE[0] <= bar['rsi'] <= TREND_RSI_LONG_RANGE[1]):  # RSI filter

                entry = bar['close']
                sl = entry - TREND_SL_ATR_MULT * atr
                tp = entry + TREND_RR_PRIMARY * (entry - sl)

                signals.append(Signal(
                    timestamp=ts, symbol=self.symbol,
                    direction=Direction.LONG, module=self.name,
                    entry_price=entry, stop_loss=sl, take_profit=tp,
                    atr_at_entry=atr, regime=Regime.TRENDING,
                    regime_confidence=regime_row['confidence'],
                ))

            # --- SHORT setup ---
            elif (h4_dir <= 0 and  # H4 not uptrending
                  bar['close'] < bar['low_20'] and  # 20-bar breakdown
                  bar['close'] < bar['ema_slow'] and  # Below EMA200
                  bar['bar_range'] > TREND_ATR_EXPANSION * bar['avg_range_5'] and
                  TREND_RSI_SHORT_RANGE[0] <= bar['rsi'] <= TREND_RSI_SHORT_RANGE[1]):

                entry = bar['close']
                sl = entry + TREND_SL_ATR_MULT * atr
                tp = entry - TREND_RR_PRIMARY * (sl - entry)

                signals.append(Signal(
                    timestamp=ts, symbol=self.symbol,
                    direction=Direction.SHORT, module=self.name,
                    entry_price=entry, stop_loss=sl, take_profit=tp,
                    atr_at_entry=atr, regime=Regime.TRENDING,
                    regime_confidence=regime_row['confidence'],
                ))

        return signals

    def _get_regime_at(self, ts, h1_regime):
        """Get the latest fully closed H1 regime prior to the completion of the 15m bar."""
        cutoff = ts - pd.Timedelta(minutes=45)
        valid = h1_regime.index[h1_regime.index <= cutoff]
        if len(valid) == 0:
            return None
        return h1_regime.loc[valid[-1]]

    def _get_h4_at(self, ts, h4_structure):
        """Get the latest fully closed H4 structure prior to the completion of the 15m bar."""
        cutoff = ts - pd.Timedelta(hours=3, minutes=45)
        valid = h4_structure.index[h4_structure.index <= cutoff]
        if len(valid) == 0:
            return 0
        return h4_structure.loc[valid[-1]]


# ============================================================
# MODULE 2 — MEAN REVERSION
# ============================================================

class MeanReversionStrategy:
    """
    Module 2: Mean Reversion
    Activation: RANGING regime with >70% confidence

    Entry: RSI extreme + BB extreme + confirmation candle
    SL: ATR(14) x 1.2 beyond BB extreme
    TP: BB midline, min 1:1.5 RR
    Time exit: 20 bars
    """

    def __init__(self, symbol: str = "EURUSD"):
        self.symbol = symbol
        self.name = "meanrev"

    def generate_signals(
        self,
        entry_df: pd.DataFrame,
        h1_regime: pd.DataFrame,
        h4_structure: pd.Series,
    ) -> list[Signal]:
        """Scan for mean reversion entries on 15m data."""
        signals = []
        df = compute_indicators(entry_df)

        for i in range(max(MR_BB_PERIOD, MR_RSI_PERIOD) + 5, len(df)):
            bar = df.iloc[i]
            prev = df.iloc[i - 1]
            ts = df.index[i]

            if pd.isna(bar['atr']) or pd.isna(bar['rsi']) or pd.isna(bar['bb_upper']):
                continue

            # --- Regime gate ---
            regime_row = self._get_regime_at(ts, h1_regime)
            if regime_row is None:
                continue
            if regime_row['regime'] != Regime.RANGING:
                continue
            if regime_row['confidence'] < HMM_MIN_CONFIDENCE:
                continue

            # --- EMA proximity check (must be ranging) ---
            if not pd.isna(bar['ema_fast']) and not pd.isna(bar['ema_slow']) and bar['atr'] > 0:
                ema_prox = abs(bar['ema_fast'] - bar['ema_slow']) / bar['atr']
                if ema_prox > EMA_PROXIMITY_THRESHOLD * 10:  # Wide EMAs = not ranging
                    continue

            atr = bar['atr']
            if atr <= 0:
                continue

            # --- LONG: oversold at lower BB ---
            if (bar['rsi'] < MR_RSI_OVERSOLD and
                prev['low'] <= prev['bb_lower'] and  # Previous touched lower BB
                bar['close'] > bar['bb_lower']):      # Confirmation: closed back inside

                entry = bar['close']
                sl = entry - MR_SL_ATR_MULT * atr
                # TP = BB midline, but ensure min RR
                tp_bb = bar['bb_mid']
                tp_min = entry + MR_MIN_RR * (entry - sl)
                tp = max(tp_bb, tp_min)

                signals.append(Signal(
                    timestamp=ts, symbol=self.symbol,
                    direction=Direction.LONG, module=self.name,
                    entry_price=entry, stop_loss=sl, take_profit=tp,
                    atr_at_entry=atr, regime=Regime.RANGING,
                    regime_confidence=regime_row['confidence'],
                ))

            # --- SHORT: overbought at upper BB ---
            elif (bar['rsi'] > MR_RSI_OVERBOUGHT and
                  prev['high'] >= prev['bb_upper'] and  # Previous touched upper BB
                  bar['close'] < bar['bb_upper']):       # Confirmation

                entry = bar['close']
                sl = entry + MR_SL_ATR_MULT * atr
                tp_bb = bar['bb_mid']
                tp_min = entry - MR_MIN_RR * (sl - entry)
                tp = min(tp_bb, tp_min)

                signals.append(Signal(
                    timestamp=ts, symbol=self.symbol,
                    direction=Direction.SHORT, module=self.name,
                    entry_price=entry, stop_loss=sl, take_profit=tp,
                    atr_at_entry=atr, regime=Regime.RANGING,
                    regime_confidence=regime_row['confidence'],
                ))

        return signals

    def _get_regime_at(self, ts, h1_regime):
        """Get the latest fully closed H1 regime prior to the completion of the 15m bar."""
        cutoff = ts - pd.Timedelta(minutes=45)
        valid = h1_regime.index[h1_regime.index <= cutoff]
        if len(valid) == 0:
            return None
        return h1_regime.loc[valid[-1]]


# ============================================================
# MODULE 3 — HIGH VOLATILITY PROTOCOL
# ============================================================

class HighVolStrategy:
    """
    Module 3: High Volatility Protocol
    Activation: HIGH_VOL regime with >70% confidence

    Entry: 20-bar breakout + 2x bar range + body ratio + ATR expansion
    SL: ATR(14) x 2.0
    TP: 1:1.5 RR minimum
    Risk: 50% of base (0.25%)
    """

    def __init__(self, symbol: str = "EURUSD"):
        self.symbol = symbol
        self.name = "highvol"

    def generate_signals(
        self,
        entry_df: pd.DataFrame,
        h1_regime: pd.DataFrame,
        h4_structure: pd.Series,
    ) -> list[Signal]:
        """Scan for high volatility entries on 15m data."""
        signals = []
        df = compute_indicators(entry_df)

        for i in range(TREND_BREAKOUT_BARS + 5, len(df)):
            bar = df.iloc[i]
            ts = df.index[i]

            if pd.isna(bar['atr']) or pd.isna(bar['avg_range_20']):
                continue

            # --- Regime gate ---
            regime_row = self._get_regime_at(ts, h1_regime)
            if regime_row is None:
                continue
            if regime_row['regime'] != Regime.HIGH_VOL:
                continue
            if regime_row['confidence'] < HMM_MIN_CONFIDENCE:
                continue

            atr = bar['atr']
            if atr <= 0:
                continue

            # Volatility expansion checks
            range_expansion = bar['bar_range'] > HV_BAR_RANGE_MULT * bar['avg_range_20']
            body_ok = bar['body_ratio'] > HV_BODY_RATIO if not pd.isna(bar['body_ratio']) else False
            atr_expanding = bar['atr_change_pct'] > HV_ATR_EXPANSION if not pd.isna(bar['atr_change_pct']) else False

            if not (range_expansion and body_ok and atr_expanding):
                continue

            # Risk is reduced by 50%
            risk = BASE_RISK_PCT * HV_RISK_REDUCTION

            # --- H4 directional filter ---
            h4_dir = self._get_h4_at(ts, h4_structure)

            # --- LONG: breakout above 20-bar high + H4 not downtrending ---
            if (bar['close'] > bar['high_20'] and bar['close'] > bar['open']
                    and h4_dir >= 0):
                entry = bar['close']
                sl = entry - HV_SL_ATR_MULT * atr
                tp = entry + HV_MIN_RR * (entry - sl)

                signals.append(Signal(
                    timestamp=ts, symbol=self.symbol,
                    direction=Direction.LONG, module=self.name,
                    entry_price=entry, stop_loss=sl, take_profit=tp,
                    risk_pct=risk, atr_at_entry=atr,
                    regime=Regime.HIGH_VOL,
                    regime_confidence=regime_row['confidence'],
                ))

            # SHORT entries disabled — optimization analysis showed HighVol shorts
            # lose in all conditions (23% WR, -208 pips) including with H4 filter.
            # Volatility breakdowns reverse too quickly for the 2×ATR stop.

        return signals

    def _get_regime_at(self, ts, h1_regime):
        valid = h1_regime.index[h1_regime.index <= ts]
        if len(valid) == 0:
            return None
        return h1_regime.loc[valid[-1]]

    def _get_h4_at(self, ts, h4_structure):
        """Get the latest fully closed H4 structure prior to the completion of the 15m bar."""
        cutoff = ts - pd.Timedelta(hours=3, minutes=45)
        valid = h4_structure.index[h4_structure.index <= cutoff]
        if len(valid) == 0:
            return 0
        return h4_structure.loc[valid[-1]]
